# List of object enabled for picking & placing
# model: gazebo model id
# default_link: gazebo link used for picking for default

objects:
 -
   model: pallet_truckcart
   default_link: link_0
 -
   model: pallet_truckcart_0
   default_link: link_0
 -
   model: pallet_truckcart_1
   default_link: link_0

robots:
- 
   model: pallet_truck_a
   default_link: pallet_truck_a_base_footprint
- 
   model: pallet_truck_b
   default_link: pallet_truck_b_base_footprint
- 
   model: pallet_truck_c
   default_link: pallet_truck_c_base_footprint

config:
  # min distance for the simple pick
  min_picking_distance: 0.1
