<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find hr_recycler_description)/urdf/elevator/elevator.urdf.xacro"/>

  <xacro:macro name="both_elevator" params="prefix parent hq *origin" >

    <xacro:property name="fork_length" value="1.176" />
    <xacro:property name="elevator_x" value="-${base_length/2.0}" />
  	<xacro:property name="elevator_y" value="0.195" />
  	<xacro:property name="elevator_z" value="0.0" />
  	<xacro:property name="fork_width" value="0.11" />
  	<xacro:property name="fork_height" value="0.05" />
  	<xacro:property name="fork_mass" value="10.0" />

    <joint name="${prefix}_both_elevator_joint" type="prismatic">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${prefix}_platform_link" />
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="0.0" upper="0.25" velocity="1.0"/>
    </joint>

    <transmission name="${prefix}both_elevator_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_both_elevator_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_both_elevator_motor">
        <hardwareInterface>hardware_interface/PositionActuatorInterface</hardwareInterface>
        <mechanicalReduction>${traction_mechanical_reduction}</mechanicalReduction>
      </actuator>
    </transmission>

    <link name="${prefix}_platform_link">
      <inertial>
        <mass value="1" />
        <origin xyz="0 0 0" />
        <cylinder_inertia m="1" r="1" h="1" />
      </inertial>
    </link>

    <xacro:elevator_platform prefix="$(arg prefix)left_fork" parent="${prefix}_platform_link" hq="${hq}">
        <origin xyz="0 ${elevator_y} -0.02" rpy="0 0 0"/>
    </xacro:elevator_platform>

    <xacro:elevator_platform prefix="$(arg prefix)right_fork" parent="${prefix}_platform_link" hq="${hq}">
        <origin xyz="0 -${elevator_y} -0.02" rpy="0 0 0"/>
    </xacro:elevator_platform>
  </xacro:macro>
</robot>
