<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find hr_recycler_description)/urdf/elevator/elevator.urdf.xacro"/>

  <xacro:macro name="both_elevator" params="prefix parent hq *origin" >

    <xacro:property name="elevator_x" value="0.0" />
  	<xacro:property name="elevator_y" value="0.195" />
  	<xacro:property name="elevator_z" value="${fork_height}" />
    <xacro:property name="fork_length" value="1.176" />
  	<xacro:property name="fork_width" value="0.11" />
  	<xacro:property name="fork_height" value="0.015" />
  	<xacro:property name="fork_mass" value="10.0" />
    <xacro:property name="fork_separation" value="0.116" />
    <xacro:property name="fork_x" value="0.0" />
    <xacro:property name="fork_y" value="0.195" />
    <xacro:property name="fork_z" value="0.0" />


    <joint name="${prefix}_both_elevator_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${prefix}_platform_link" />
    </joint>


    <link name="${prefix}_platform_link">
      <inertial>
        <mass value="1" />
        <origin xyz="0 0 0" />
        <cylinder_inertia m="1" r="1" h="1" />
      </inertial>
    </link>

    <xacro:elevator_platform prefix="$(arg prefix)left_fork" parent="${prefix}_platform_link" hq="${hq}">
        <origin xyz="${fork_x} ${fork_y} ${fork_z}" rpy="0 0 0"/>
    </xacro:elevator_platform>

    <xacro:elevator_platform prefix="$(arg prefix)right_fork" parent="${prefix}_platform_link" hq="${hq}">
        <origin xyz="${fork_x} -${fork_y} ${fork_z}" rpy="0 0 0"/>
    </xacro:elevator_platform>

    <joint name="${prefix}_prismatic_both_forks_joint" type="prismatic">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="${prefix}_platform_link"/>
        <child link="${prefix}_prismatic_forks_link" />
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="0.0" upper="0.25" velocity="1"/>
    </joint>

    <transmission name="${prefix}_prismatic_both_forks_joint_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_prismatic_both_forks_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_prismatic_both_forks_joint_motor">
        <hardwareInterface>hardware_interface/PositionActuatorInterface</hardwareInterface>
        <mechanicalReduction>${traction_mechanical_reduction}</mechanicalReduction>
      </actuator>
    </transmission>

    <link name="${prefix}_prismatic_forks_link">
      <inertial>
        <mass value="${fork_mass}" />
        <origin xyz="0 0 1" />
        <solid_cuboid_inertia m="${fork_mass/2.0}" h="${fork_height}" d="${fork_length}" w="${fork_width}"/>
      </inertial>
    </link>

    <joint name="${prefix}_prismatic_left_fork_joint" type="fixed">
        <origin xyz="${elevator_x} ${elevator_y} ${elevator_z}" rpy="0 0 0"/>
        <parent link="${prefix}_prismatic_forks_link"/>
        <child link="${prefix}_prismatic_left_fork" />
    </joint>


    <link name="${prefix}_prismatic_left_fork">
      <visual>
        <origin xyz="-${fork_length/2} 0 0" rpy="0 0 0" />
        <xacro:if value="${hq}">
          <geometry>
            <!--mesh filename="package://hr_recycler_description/meshes/elevator/hr_recycler_elevator.dae"/-->
            <box size="${fork_length} ${fork_width} ${fork_height}"/>
          </geometry>
        </xacro:if>
        <xacro:unless value="${hq}">
          <geometry>
            <!--mesh filename="package://hr_recycler_description/meshes/elevator/hr_recycler_elevator.stl"/-->
            <box size="${fork_length} ${fork_width} ${fork_height}"/>
          </geometry>
        </xacro:unless>
        <material name="black">
          <color rgba="0.0 0.0 0.0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="-${fork_length/2} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${fork_length} ${fork_width} ${fork_height}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${fork_mass}" />
        <origin xyz="0 0 0" />
        <solid_cuboid_inertia m="${fork_mass}" h="${fork_height}" d="${fork_length}" w="${fork_width}"/>
      </inertial>
    </link>

    <joint name="${prefix}_prismatic_right_fork_joint" type="fixed">
        <origin xyz="${elevator_x} -${elevator_y} ${elevator_z}" rpy="0 0 0"/>
        <parent link="${prefix}_prismatic_forks_link"/>
        <child link="${prefix}_prismatic_right_fork" />
    </joint>


    <link name="${prefix}_prismatic_right_fork">
      <visual>
        <origin xyz="-${fork_length/2} 0 0" rpy="0 0 0" />
        <xacro:if value="${hq}">
          <geometry>
            <!--mesh filename="package://hr_recycler_description/meshes/elevator/hr_recycler_elevator.dae"/-->
            <box size="${fork_length} ${fork_width} ${fork_height}"/>
          </geometry>
        </xacro:if>
        <xacro:unless value="${hq}">
          <geometry>
            <!--mesh filename="package://hr_recycler_description/meshes/elevator/hr_recycler_elevator.stl"/-->
            <box size="${fork_length} ${fork_width} ${fork_height}"/>
          </geometry>
        </xacro:unless>
        <material name="black">
          <color rgba="0.0 0.0 0.0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="-${fork_length/2} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${fork_length} ${fork_width} ${fork_height}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${fork_mass}" />
        <origin xyz="0 0 0" />
        <solid_cuboid_inertia m="${fork_mass}" h="${fork_height}" d="${fork_length}" w="${fork_width}"/>
      </inertial>
    </link>


  </xacro:macro>
</robot>
