<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find hr_recycler_description)/urdf/wheels/omni_wheel.urdf.xacro" />

  <!-- Fork measurements -->
  <xacro:property name="fork_length" value="1.176" />
	<xacro:property name="fork_width" value="0.11" />
	<xacro:property name="fork_height" value="0.015" />
	<xacro:property name="fork_mass" value="2.0" />

  <!-- Fork positions -->
  <xacro:property name="fork_x" value="0.0" />
  <xacro:property name="fork_y" value="0.195" />
  <xacro:property name="fork_z" value="0.0" />

  <!-- Support wheel position -->
  <xacro:property name="support_wheel_origin" value="-1.3175 0.0 ${wheel_radius/4.0-0.005}" />
  <!-- Limit elevator -->
  <xacro:property name="upper_limit_elevator" value="0.07" />

  <!-- Inertial equation depending of forms -->
  <xacro:macro name="solid_cuboid_inertia" params="m h d w">
   <inertia  ixx="${(m*(h*h+d*d))/12}" ixy = "0" ixz = "0"
             iyy="${(m*(w*w+d*d))/12}" iyz = "0"
             izz="${(m*(w*w+h*h))/12}"
    />
  </xacro:macro>

  <!-- Platform is divided into two parts: TOP PLATFORM with a prismatic
   joint, BELOW PLATFORM which has the two support wheels.-->

  <!-- ************** -->
  <!-- BELOW PLATFORM -->
  <!-- ************** -->
  <xacro:macro name="elevator_platform" params="prefix parent hq *origin">

  	<joint name="${prefix}foot_elevator_joint" type="fixed">
  			<xacro:insert_block name="origin" />
  			<parent link="${parent}"/>
  			<child link="${prefix}foot_elevator_link" />
  	</joint>

  	<link name="${prefix}foot_elevator_link">
  	</link>

    <!-- Support wheel -->
  	<xacro:omni_wheel prefix="${prefix}omni" parent="${prefix}foot_elevator_link" hq="${hq}">
  			<origin xyz="${support_wheel_origin}" rpy="0 0 0"/>
  	</xacro:omni_wheel>

  </xacro:macro>

  <!-- ************** -->
  <!--    PLATFORM    -->
  <!-- ************** -->
  <xacro:macro name="elevator" params="prefix parent hq *origin" >

    <joint name="${prefix}elevator_base_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${prefix}elevator_base_link" />
    </joint>
    
    <link name="${prefix}elevator_base_link" >
      <inertial>
        <mass value="1" />
        <origin xyz="0 0 0" />
        <box_inertia  m="0.001" x="0.001" y="0.001" z="0.001"/>
      </inertial>
    </link> 

    <joint name="${prefix}elevator_joint" type="prismatic">
        <parent link="${prefix}elevator_base_link"/>
        <child link="${prefix}elevator_link" />
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="0.0" upper="${upper_limit_elevator}" velocity="1"/>
    </joint>

    <!-- This piece supports the two lower forks -->
    <link name="${prefix}elevator_link">
      <visual>
        <origin xyz="0 0 0.410" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://hr_recycler_description/meshes/bases/base.stl" scale="-1 1 1"/>
        </geometry>
         <material name="darkgrey">
           <color rgba="0.1 0.1 0.1 1"/>
         </material>
      </visual>
      <inertial>
        <mass value="1" />
        <origin xyz="-0.8 0 0" />
        <box_inertia  m="1" x="1.67" y="0.1" z="0.03"/>
      </inertial>
      <collision>
        <origin xyz="0 0 0.410" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://hr_recycler_description/meshes/bases/base.stl" scale="-1 1 1"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}forks_joint" type="fixed">
       <xacro:insert_block name="origin" />
       <parent link="${prefix}elevator_link"/>
       <child link="${prefix}forks_link" />
     </joint>

     <!-- This piece holds the forks that are going to be elevated -->
     <link name="${prefix}forks_link">
       <inertial>
         <mass value="1" />
         <origin xyz="-0.2 0 0" />
         <solid_cuboid_inertia m="${fork_mass}" h="${fork_height}" d="${fork_length}" w="${fork_width}"/>
       </inertial>
       <visual>
         <origin xyz="-1.3725 0 0.080" rpy="0 0 0" />
         <geometry>
           <mesh filename="package://hr_recycler_description/meshes/elevator/hr_recycler_forks.stl" scale="-1 1 1"/>
         </geometry>
          <material name="darkgrey">
            <color rgba="0.1 0.1 0.1 1"/>
          </material>
       </visual>
       <collision>
         <origin xyz="-1.3725 0 0.080" rpy="0 0 0" />
         <geometry>
           <mesh filename="package://hr_recycler_description/meshes/elevator/hr_recycler_forks.stl" scale="-1 1 1"/>
         </geometry>
         <surface>
           <friction>
             <ode>
               <mu>100000</mu>
               <mu2>50000</mu2>
             </ode>
           </friction>
         </surface>
       </collision>
     </link>

    <!-- Called two lower forks -->
    <xacro:elevator_platform prefix="${prefix}left_" parent="${prefix}base_footprint" hq="${hq}">
        <origin xyz="${fork_x} ${fork_y} ${fork_z}" rpy="0 0 0"/>
    </xacro:elevator_platform>

    <xacro:elevator_platform prefix="${prefix}right_" parent="${prefix}base_footprint" hq="${hq}">
        <origin xyz="${fork_x} -${fork_y} ${fork_z}" rpy="0 0 0"/>
    </xacro:elevator_platform>

    <!-- ************* -->
    <!-- TRANSMISSIONS -->
    <!-- ************* -->
     <transmission name="${prefix}elevator_joint_transmission">
       <type>transmission_interface/SimpleTransmission</type>
       <joint name="${prefix}elevator_joint">
         <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
       </joint>
       <actuator name="${prefix}elevator_joint_motor">
         <hardwareInterface>hardware_interface/PositionActuatorInterface</hardwareInterface>
         <mechanicalReduction>${traction_mechanical_reduction}</mechanicalReduction>
       </actuator>
     </transmission>

  </xacro:macro>
</robot>
