<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


	<xacro:include filename="$(find hr_recycler_description)/urdf/elevator/elevator.transmission.xacro"/>
	<xacro:include filename="$(find hr_recycler_description)/urdf/elevator/elevator.gazebo.xacro"/>

	<xacro:macro name="elevator_platform" params="prefix parent hq *origin">

	<xacro:property name="fork_length" value="1.176" />
	<xacro:property name="fork_width" value="0.11" />
	<xacro:property name="fork_height" value="0.05" />
	<xacro:property name="fork_mass" value="25.0" />

	<xacro:property name="fork_separation" value="0.116" />

	<xacro:property name="support_wheel_radius" value="${wheel_radius/2.0-fork_height/4.0}" />
	<xacro:property name="support_wheel_length" value="${fork_width}" />
  <xacro:property name="support_wheel_mass" value="5.0" />

	<xacro:property name="support_wheel_joint_x" value="${0.16-fork_length}" />
	<xacro:property name="support_wheel_joint_y" value="0.0" />
	<xacro:property name="support_wheel_joint_z" value="-${wheel_radius/2.0+fork_height/4.0}" />

	<!-- PARAMS: -->
	<!-- name : name of the link: -->
	<!-- hq: selects model in high quality (.dae) -->


   <xacro:macro name="solid_cuboid_inertia" params="m h d w">
    <inertia  ixx="${(m*(h*h+d*d))/12}" ixy = "0" ixz = "0"
              iyy="${(m*(w*w+d*d))/12}" iyz = "0"
              izz="${(m*(w*w+h*h))/12}"
     />
  </xacro:macro>

	<!-- ELEVATOR PLATFORM -->
	<joint name="${prefix}_platform_joint" type="prismatic">
			<xacro:insert_block name="origin" />
			<parent link="${parent}"/>
			<child link="${prefix}_platform_link" />
			<axis xyz="0 0 1"/>
			<limit effort="1000.0" lower="0.0" upper="1.0" velocity="0.01"/>
	</joint>
	<link name="${prefix}_platform_link">
		<visual>
			<origin xyz="-${fork_length/2} 0 0" rpy="0 0 0" />
			<xacro:if value="${hq}">
				<geometry>
					<!--mesh filename="package://hr_recycler_description/meshes/elevator/hr_recycler_elevator.dae"/-->
					<box size="${fork_length} ${fork_width} ${fork_height}"/>
				</geometry>
			</xacro:if>
			<xacro:unless value="${hq}">
				<geometry>
					<!--mesh filename="package://hr_recycler_description/meshes/elevator/hr_recycler_elevator.stl"/-->
					<box size="${fork_length} ${fork_width} ${fork_height}"/>
				</geometry>
			</xacro:unless>
			<material name="black">
				<color rgba="0.0 0.0 0.0 1"/>
			</material>
		</visual>
		<collision>
			<origin xyz="-${fork_length/2} 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${fork_length} ${fork_width} ${fork_height}"/>
			</geometry>
			<!--geometry>
					<mesh filename="package://hr_recycler_description/meshes/elevator/hr_recycler_elevator.dae"/>
				</geometry-->
		</collision>
		<inertial>
			<mass value="${fork_mass}" />
			<origin xyz="0 0 -0.27" />
			<solid_cuboid_inertia m="${fork_mass}" h="${fork_height}" d="${fork_length}" w="${fork_width}"/>
		</inertial>
	</link>

	<joint name="${prefix}_support_wheel_joint" type="continuous">
			<origin xyz="${support_wheel_joint_x} ${support_wheel_joint_y} ${support_wheel_joint_z}" rpy="0 0 0"/>
			<parent link="${prefix}_platform_link"/>
			<child link="${prefix}_support_wheel_link" />
			<axis xyz="0 1 0" rpy="0 0 0" />
	</joint>
	<link name="${prefix}_support_wheel_link">
		<visual>
				<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
				<geometry>
					<cylinder radius="${support_wheel_radius}" length="${support_wheel_length}"/>
					<!--sphere radius="${support_wheel_radius}"/-->
				</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
			<geometry>
				<cylinder radius="${support_wheel_radius}" length="${support_wheel_length}"/>
				<!--sphere radius="${support_wheel_radius}" /-->
			</geometry>
		</collision>
		<inertial>
			<mass value="${support_wheel_mass}" />
			<origin xyz="0 0 0" />
			<cylinder_inertia m="${support_wheel_mass}" r="${support_wheel_length}" h="${support_wheel_length}" />
		</inertial>
	</link>

        <!--transmission name="${prefix}_support_wheel_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_support_wheel_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_support_wheel_motor">
        <hardwareInterface>hardware_interface/EffortActuatorInterface</hardwareInterface>
        <mechanicalReduction>${traction_mechanical_reduction}</mechanicalReduction>
      </actuator>
    </transmission-->

	<!--xacro:elevator_transmission prefix="${prefix}" /-->
	<!--xacro:elevator_gazebo prefix="${prefix}" /-->

	</xacro:macro>



</robot>
