<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


	<xacro:include filename="$(find hr_recycler_description)/urdf/elevator/elevator.transmission.xacro"/>
	<xacro:include filename="$(find hr_recycler_description)/urdf/elevator/elevator.gazebo.xacro"/>

	<xacro:macro name="elevator_platform" params="prefix parent hq *origin">

	<xacro:property name="fork_length" value="1.176" />
	<xacro:property name="fork_width" value="0.11" />
	<xacro:property name="fork_height" value="0.05" />
	<xacro:property name="fork_separation" value="0.116" />
	<!-- PARAMS: -->
	<!-- name : name of the link: -->
	<!-- hq: selects model in high quality (.dae) -->


   <xacro:macro name="solid_cuboid_inertia" params="m h d w">
    <inertia  ixx="${(m*(h*h+d*d))/12}" ixy = "0" ixz = "0"
              iyy="${(m*(w*w+d*d))/12}" iyz = "0"
              izz="${(m*(w*w+h*h))/12}"
     />
  </xacro:macro>

	<!-- ELEVATOR PLATFORM -->
	<joint name="${prefix}_platform_joint" type="fixed">
			<xacro:insert_block name="origin" />
			<parent link="${parent}"/>
			<child link="${prefix}_platform_link" />
			<axis xyz="0 0 1"/>
			<limit effort="1000.0" lower="0.0" upper="0.05" velocity="0.01"/>
	</joint>
	<link name="${prefix}_platform_link">
		<visual>
			<origin xyz="-${fork_length/2} 0 0" rpy="0 0 0" />
			<xacro:if value="${hq}">
				<geometry>
					<!--mesh filename="package://hr_recycler_description/meshes/elevator/hr_recycler_elevator.dae"/-->
					<box size="${fork_length} ${fork_width} ${fork_height}"/>
				</geometry>
			</xacro:if>
			<xacro:unless value="${hq}">
				<geometry>
					<!--mesh filename="package://hr_recycler_description/meshes/elevator/hr_recycler_elevator.stl"/-->
					<box size="${fork_length} ${fork_width} ${fork_height}"/>
				</geometry>
			</xacro:unless>
			<material name="black">
				<color rgba="0.0 0.0 0.0 1"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 -0.0" rpy="0 0 0 " />
			<geometry>
				<box size="0.65 0.5 0.025" />
			</geometry>
			<!--geometry>
					<mesh filename="package://hr_recycler_description/meshes/elevator/hr_recycler_elevator.dae"/>
				</geometry-->
		</collision>
		<inertial>
			<mass value="0.005" />
			<origin xyz="0 0 -0.27" />
			<solid_cuboid_inertia m="0.005" h="0.05" d="0.05" w="0.05"/>
		</inertial>
	</link>

	<!--xacro:elevator_transmission prefix="${prefix}" /-->
	<!--xacro:elevator_gazebo prefix="${prefix}" /-->

	</xacro:macro>



</robot>
