gazebo_ros_control:
  pid_gains:
#    pallet_truck_backwheel_steer_joint:
#      p: 100
#      i: 0.01
#      d: 10.0

#    pallet_truck_both_forks_prismatic_both_forks_joint:
#      p: 100.0
#      i: 0.01
#      d: 10.0


