<?xml version="1.0"?>
<robot name="hr_recycler" xmlns:xacro="http://www.ros.org/wiki/xacro"> 

  <xacro:macro name="hr_recycler" params="prefix publish_bf hq">

  <!-- Robot mechanical and motor parameters -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="wheel_width" value="0.220" />
  <xacro:property name="wheel_radius" value="0.10" />

  <xacro:property name="base_length" value="0.679" />
  <xacro:property name="base_width" value="0.754" />
  <xacro:property name="base_height" value="0.533" />
  <xacro:property name="base_mass" value="1.0"/>

  <xacro:property name="fork_length" value="1.176" />
  <xacro:property name="fork_width" value="0.11" />
  <xacro:property name="fork_height" value="0.05" />
  <xacro:property name="fork_separation" value="0.116" />

  <xacro:macro name="box_inertia" params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
              iyy="${m*(x*x+z*z)/12}" iyz = "0"
              izz="${m*(x*x+z*z)/12}" /> 
  </xacro:macro>

  <!-- BASE FOOTPRINT -->
  <xacro:if value="${publish_bf}">
    <link name="${prefix}base_footprint">
      <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
             <box size="0.001 0.001 0.001" />
          </geometry>
      </visual>
    </link>

    <joint name="${prefix}base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
      <parent link="${prefix}base_footprint"/>
      <child link="${prefix}base_link" />
    </joint>    
  </xacro:if>

  <!-- BASE_LINK -->
  <link name="${prefix}base_link">
    <inertial>
      <mass value="${base_mass}" />
      <origin xyz="0 0 0" />
      <box_inertia  m="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}"/>
    </inertial>
    <visual>
       <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
       <xacro:if value="${hq}">
         <geometry>
		   <!--<mesh filename="package://hr_recycler_description/meshes/bases/hr_recycler_base.stl"/>-->
	       <box size="${base_length} ${base_width} ${base_height}"/>
         </geometry>
       </xacro:if>
       <xacro:unless value="${hq}">
         <geometry>
           <!--<mesh filename="package://hr_recycler_description/meshes/bases/hr_recycler.stl"/>-->
	       <box size="0.679 0.754 0.533"/>
         </geometry>
       </xacro:unless>
       <material name="darkgrey">
         <color rgba="0.1 0.1 0.1 1"/>
       </material>
    </visual>  
  </link>

  </xacro:macro>
</robot>

