# List of object enabled for picking & placing
# model: gazebo model id
# default_link: gazebo link used for picking for default

objects:
 -
   model: hr_recyclercart
   default_link: link_0
 -
   model: hr_recyclercart_0
   default_link: link_0
 -
   model: hr_recyclercart_1
   default_link: link_0

robots:
- 
   model: hr_recycler_a
   default_link: hr_recycler_a_base_footprint
- 
   model: hr_recycler_b
   default_link: hr_recycler_b_base_footprint
- 
   model: hr_recycler_c
   default_link: hr_recycler_c_base_footprint

config:
  # min distance for the simple pick
  min_picking_distance: 0.1
