<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find pallet_truck_description)/urdf/wheels/omni_wheel.urdf.xacro" />

  <xacro:property name="PI" value="3.1415926535897931"/>

  <!-- Fork measurements -->
  <xacro:property name="fork_length" value="1.176" />
	<xacro:property name="fork_width" value="0.11" />
	<xacro:property name="fork_height" value="0.015" />
	<xacro:property name="fork_mass" value="20" />

  <!-- Fork positions -->
  <xacro:property name="fork_x" value="0.0" />
  <xacro:property name="fork_y" value="0.195" />
  <xacro:property name="fork_z" value="0.0" />

  <!-- Support wheel -->
  <xacro:property name="support_wheel_mass" value="1" />
  <xacro:property name="support_wheel_length" value="0.07" />
  <xacro:property name="support_wheel_radius" value="0.04" />

  <!-- Limit elevator -->
  <xacro:property name="upper_limit_elevator" value="0.07" />

  <!-- *************** -->
  <!--  SUPPORT WHEEL  -->
  <!-- *************** -->
  <xacro:macro name="support_wheel" params="prefix parent hq *origin">

  	<joint name="${prefix}wheel_joint" type="continuous">
  			<xacro:insert_block name="origin" />
        <axis xyz="0 1 0"/>
  			<parent link="${parent}"/>
  			<child link="${prefix}wheel_link" />
        <limit effort="1.0" velocity="1"/>
  	</joint>

  	<link name="${prefix}wheel_link">
      <inertial>
        <mass value="${support_wheel_mass}" />
        <origin xyz="0 0 0" rpy="${PI/2.0} 0 0"/>
        <cylinder_inertia  m="${support_wheel_mass}" r="${support_wheel_radius}" h="${support_wheel_length}" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2.0} 0 0" />
        <geometry>
           <cylinder radius="${support_wheel_radius}" length="${support_wheel_length}" />
        </geometry>
        <material name="darkgrey">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2.0} 0 0"/>
        <geometry>
          <cylinder radius="${support_wheel_radius}" length="${support_wheel_length}" />
        </geometry>
      </collision>
  	</link>

    <!-- ***************** -->
    <!-- GAZEBO PROPERTIES -->
    <!-- ***************** -->

    <!-- TRACTION LINK -->
    <gazebo reference="${prefix}wheel_link">
      <mu1>3</mu1>
      <mu2>2</mu2>
      <material>Gazebo/Black</material>
    </gazebo>

    <!-- ************* -->
    <!-- TRANSMISSIONS -->
    <!-- ************* -->
     <transmission name="${prefix}wheel_joint_transmission">
       <type>transmission_interface/SimpleTransmission</type>
       <joint name="${prefix}wheel_joint">
         <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
       </joint>
       <actuator name="${prefix}wheel_joint_motor">
         <hardwareInterface>hardware_interface/VelocityActuatorInterface</hardwareInterface>
         <mechanicalReduction>${traction_mechanical_reduction}</mechanicalReduction>
       </actuator>
     </transmission>

  </xacro:macro>

  <xacro:macro name="fork" params="prefix parent hq *origin">
    <joint name="${prefix}fork_joint" type="prismatic">
  	   <xacro:insert_block name="origin" />
       <parent link="${parent}"/>
       <child link="${prefix}fork_link" />
       <limit effort="1000.0" lower="0.0" upper="0" velocity="1"/>

     </joint>

     <!-- This piece holds the forks that are going to be elevated -->
     <link name="${prefix}fork_link">
       <inertial>
         <mass value="${fork_mass}" />
         <origin xyz="${fork_length/2.0} 0.0 0.0" />
         <!-- yes, axis in solid_cuboid_inertia are changed, w relates to X axis, d to Z axis, and h to Y axis -->
         <!-- Keep this comment -->
         <solid_cuboid_inertia m="${fork_mass}" h="${fork_width}" d="${fork_height}" w="${fork_length}"/>
       </inertial>
       <visual>
         <!--<origin xyz="${fork_length} 0 0" rpy="0 0 0" />-->
         <!--<geometry>-->
           <!--<mesh filename="package://pallet_truck_description/meshes/elevator/single_fork.stl"/>-->
         <!--</geometry>-->
         <origin xyz="${fork_length/2.0} 0.0 0.0" rpy="0 0 0" />
         <geometry>
            <box size="${fork_length} ${fork_width} ${fork_height}" />
         </geometry>
         <material name="darkgrey">
           <color rgba="0.1 0.1 0.1 1.0"/>
         </material>
       </visual>
       <collision>
         <origin xyz="${fork_length/2.0} 0.0 0.0" rpy="0 0 0" />
         <geometry>
            <box size="${fork_length} ${fork_width} ${fork_height}" />
         </geometry>
       </collision>
     </link>

     <!-- ***************** -->
     <!-- GAZEBO PROPERTIES -->
     <!-- ***************** -->

     <!-- FORK LINK -->
     <gazebo reference="${prefix}fork_link">
       <mu1>100000</mu1>
       <mu2>100000</mu2>
       <material>Gazebo/Black</material>
     </gazebo>

  </xacro:macro>

  <!-- ************** -->
  <!--    PLATFORM    -->
  <!-- ************** -->
  <xacro:macro name="elevator" params="prefix parent hq *origin" >

    <joint name="${prefix}elevator_base_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${prefix}elevator_base_link" />
    </joint>

    <link name="${prefix}elevator_base_link" >
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" />
         <!-- yes, axis in solid_cuboid_inertia are changed, w relates to X axis, d to Z axis, and h to Y axis -->
         <!-- Keep this comment -->
         <solid_cuboid_inertia m="0.001" h="0.001" d="0.001" w="0.001"/>
      </inertial>
    </link>

    <joint name="${prefix}elevator_joint" type="prismatic">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="${prefix}elevator_base_link"/>
        <child link="${prefix}elevator_link" />
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="0.0" upper="${upper_limit_elevator}" velocity="1"/>
    </joint>

    <!-- This piece supports the two lower forks -->
    <link name="${prefix}elevator_link">
      <visual>
        <geometry>
          <mesh filename="package://pallet_truck_description/meshes/bases/cover.stl"/>
        </geometry>
        <material name="darkgrey">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
      </visual>
      <inertial>
        <mass value="20" />
         <!-- yes, axis in solid_cuboid_inertia are changed, w relates to X axis, d to Z axis, and h to Y axis -->
         <!-- Keep this comment -->
         <solid_cuboid_inertia m="20" w="0.6" h="0.6" d="0.6"/>
      </inertial>
      <collision>
        <geometry>
          <mesh filename="package://pallet_truck_description/meshes/bases/cover.stl"/>
        </geometry>
      </collision>
    </link>

    <xacro:fork prefix="${prefix}left_" parent="${prefix}elevator_link" hq="${hq}">
       <origin xyz="0.349 -0.195 -0.3725" rpy="0 0 0" />
    </xacro:fork>

    <xacro:fork prefix="${prefix}right_" parent="${prefix}elevator_link" hq="${hq}">
       <origin xyz="0.349 0.195 -0.3725" rpy="0 0 0" />
    </xacro:fork>

    <!-- Called two support wheels -->
    <xacro:support_wheel prefix="${prefix}left_" parent="${prefix}base_footprint" hq="${hq}">
        <origin xyz="1.3725 0.195 0.04" rpy="0 0 0"/>
    </xacro:support_wheel>

    <xacro:support_wheel prefix="${prefix}right_" parent="${prefix}base_footprint" hq="${hq}">
        <origin xyz="1.3725 -0.195 0.04" rpy="0 0 0"/>
    </xacro:support_wheel>

    <!-- ************* -->
    <!-- TRANSMISSIONS -->
    <!-- ************* -->
     <transmission name="${prefix}elevator_joint_transmission">
       <type>transmission_interface/SimpleTransmission</type>
       <joint name="${prefix}elevator_joint">
         <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
       </joint>
       <actuator name="${prefix}elevator_joint_motor">
         <hardwareInterface>hardware_interface/PositionActuatorInterface</hardwareInterface>
         <mechanicalReduction>${traction_mechanical_reduction}</mechanicalReduction>
       </actuator>
     </transmission>

  </xacro:macro>
</robot>
